# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClientFirstLesson' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKClientFirstLesson
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  
end
